# Generated by Django 2.2 on 2021-08-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=20)),
                ('last_name', models.TextField(max_length=20)),
                ('date_of_birth', models.TextField()),
                ('grade', models.IntegerField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
