# Generated by Django 2.2 on 2021-10-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_auto_20211007_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
    ]
